name: guarded_core
description: Core implementation of widget guards for flutter with riverpod usage
version: 0.1.1
repository: https://github.com/massa-org/guarded_core

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
