name: guarded_core
description: Core implementation of widget guards for flutter with riverpod usage
version: 0.4.2
repository: https://github.com/massa-org/guarded_core

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  freezed_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.0.0
